name: Build and Release DLL

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v1.0.3)"
        required: true
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: ${{ github.event.inputs.tag || github.ref_name }}
            files: bin/Release/netstandard2.0/WobblyMenu.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}